spring:
  main:
    banner-mode: off

app:
  file-manager:
    default:
      yamlFile:
        prefixFileToGet: values-
      file:
        ext: env
        pattern: <profile><appName>
        directory: '.'

  progress-bar:
    min: 0
    max: 100
    step: 2
    listener:
      # Time in miliseconds
      duration: 100
      socket-port: 10000
